Repository Appsilon/shiny.gosling, pull requests merged in 2022-11, with the labels that each got.

#50 docs: replace old gifs in Readme with new ones
  README.md
Labels: documentation

#56 tests: Adding tests
  DESCRIPTION
  tests/testthat/test-add_multi_tracks.R
  tests/testthat/test-add_single_track.R
  tests/testthat/test-json_list.R
  tests/testthat/test-list_rm_null.R
Labels: tests

#40 Long line lint fixes
  R/composition.R
  R/data.R
  R/export_pdf.R
  R/export_png.R
  R/marks.R
  R/shiny.R
  R/styleProps.R
  R/utils.R
  R/visualChannels.R
  R/zoom_to.R
  R/zoom_to_extent.R
  inst/examples/circularLinearWithBrush/server.R
  inst/examples/multiTrackApp/server.R
  man/add_mark.Rd
  man/add_single_track.Rd
  man/brush_styles.Rd
  man/build_json.Rd
  man/default_track_styles.Rd
  man/event_styles.Rd
  man/export_pdf.Rd
  man/export_png.Rd
  man/gosling.Rd
  man/renderGosling.Rd
  man/track_data.Rd
  man/track_data_transform.Rd
  man/use_gosling.Rd
  man/visual_channel.Rd
  man/visual_channel_color.Rd
  man/visual_channel_opacity.Rd
  man/visual_channel_row.Rd
  man/visual_channel_size.Rd
  man/visual_channel_stroke.Rd
  man/visual_channel_stroke_width.Rd
  man/visual_channel_text.Rd
  man/visual_channel_tooltip.Rd
  man/visual_channel_x.Rd
  man/visual_channel_y.Rd
  man/zoom_to.Rd
  man/zoom_to_extent.Rd
Labels: bug

#41 Vignettes
  DESCRIPTION
  inst/examples/multiTrackApp/data/driver.df.scanb.complete.csv
  inst/examples/multiTrackApp/server.R
  vignettes/.gitignore
  vignettes/intro.Rmd
Labels: documentation

#53 doc: add orcid
  DESCRIPTION
Labels: documentation
